"""post table

Revision ID: 19a964a460e1
Revises: f6c83c9f2af5
Create Date: 2020-03-07 15:25:54.216622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19a964a460e1'
down_revision = 'f6c83c9f2af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrations')
    op.drop_index('source_index', table_name='source')
    op.create_unique_constraint(None, 'source', ['url'])
    op.create_unique_constraint(None, 'source', ['feed_link'])
    op.drop_index('source_subscription_index', table_name='source_subscription')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index('user_index', table_name='user')
    op.create_unique_constraint(None, 'user', ['social_id'])
    # ### end Alembic commands ###

    op.create_table('post',
        sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
        sa.Column('source_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
        sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('content', mysql.TEXT(), nullable=False),
        sa.Column('link', mysql.VARCHAR(length=2000), nullable=False),
        sa.Column('author', mysql.VARCHAR(length=255), nullable=False),

        sa.Column('fetched_at', mysql.TIMESTAMP(), nullable=True),
        sa.Column('published_at', mysql.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_unicode_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    op.create_index('post_index', 'post', ['source_id', 'fetched_at', 'published_at'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('user_index', 'user', ['email'], unique=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.create_index('source_subscription_index', 'source_subscription', ['user_id', 'source_id'], unique=False)
    op.drop_constraint(None, 'source', type_='unique')
    op.drop_constraint(None, 'source', type_='unique')
    op.create_index('source_index', 'source', ['created_at', 'updated_at'], unique=False)
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
    
    op.drop_index("post_index")
    op.drop_table('post')