"""post full text

Revision ID: 2646aacdec20
Revises: 19a964a460e1
Create Date: 2020-03-19 22:05:01.907419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2646aacdec20'
down_revision = '19a964a460e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_index('post_index', table_name='post')
    op.create_foreign_key(None, 'post', 'source', ['source_id'], ['id'])
    # ### end Alembic commands ###

    op.create_index('source_search', 'source', ['name', 'description', 'url', 'feed_link'], mysql_prefix='FULLTEXT')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_index('post_index', 'post', ['source_id', 'fetched_at', 'published_at'], unique=False)
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###
  
    op.drop_index('source_search', table_name='source')